### ISSUE TITLE
inspectdb: TypeError: get_meta() takes at least 3 arguments

### ISSUE THREAD

**Issue by philchristensen** [django-salesforce/django-salesforce#138]
Getting an error in the Travis build, although it doesn't seem to be affecting the build state.

```shell
$ bash tests/inspectdb/test.sh
Patched socket to IPv4 only
attempting authentication to https://login.salesforce.com
successfully authenticated djangosalesforce@gmail.com.dev
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/travis/build/django-salesforce/django-salesforce/salesforce/management/commands/inspectdb.py", line 94, in handle_noargs
    for line in self.handle_inspection(options):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/commands/inspectdb.py", line 140, in handle_inspection
    for meta_line in self.get_meta(table_name):
TypeError: get_meta() takes at least 3 arguments (2 given)
```

**Comment by hynekcer** [comment]
That's odd because it is a line from code before commit 5f1d615e18.

**Comment by philchristensen** [comment]
Line 140 wasn't edited as part as that commit though. FWIW, here's the Travis line:

https://travis-ci.org/django-salesforce/django-salesforce/builds/96303427#L173

**Comment by hynekcer** [comment]
Aha, this was a line from Django, not from our SF. The fix should be

    -    def get_meta(self, table_name, constraints, column_to_field_name=None):
    +    def get_meta(self, table_name, constraints=None, column_to_field_name=None):

The problem was that the signature of "get_meta" has changed and we should use neither the old signature with new Django or the new with old Django, but we can use a general, because we don't use any ot these optional parameters, we must only accept them.

**Comment by philchristensen** [comment]
Perfect, that did the trick.
