### ISSUE TITLE
Django 1.10: deferred_class_factory no longer exists

### ISSUE THREAD

**Issue by philchristensen** [django-salesforce/django-salesforce#160]
After (accidentally) upgrading to Django 1.10, I got a failure in `manage.py migrate` due to a broken import:

```
+ python manage.py migrate --noinput
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/base.py", line 353, in execute
    self.check()
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/models/base.py", line 1266, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/models/base.py", line 1337, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 893, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 208, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 310, in _check_backend_specific_checks
    if router.allow_migrate(db, app_label, model_name=self.model._meta.model_name):
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/django/db/utils.py", line 300, in allow_migrate
    allow = method(db, app_label, **hints)
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/salesforce/router.py", line 87, in allow_migrate
    if is_sf_database(db):
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/salesforce/router.py", line 23, in is_sf_database
    from salesforce.backend.base import DatabaseWrapper
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/salesforce/backend/base.py", line 31, in <module>
    from salesforce.backend.introspection import DatabaseIntrospection
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/salesforce/backend/introspection.py", line 24, in <module>
    from salesforce.backend import compiler, query
  File "/var/lib/jenkins/shiningpanda/jobs/b8384f38/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/salesforce/backend/query.py", line 25, in <module>
    from django.db.models.query_utils import deferred_class_factory
ImportError: cannot import name deferred_class_factory
```

I haven't had a moment to investigate it closer to see if deferred_class_factory has just moved to another module. Sooner or later I know we might run into issues with all the various changes in the Django ORM since 1.8 and have some issues.

**Comment by hynekcer** [comment]
Perfect. I'm finishing the version 0.7 that supports Django 1.10.  You can try my branch [ver-07](https://github.com/hynekcer/django-salesforce/tree/ver-07). It is today frequently rewritten, many debug print lines etc. should be removed, but every commit can now successfully run tox and known bugs are marked in tests by QUIET_KNOWN_BUGS or if you run `QUIET_KNOWN_BUGS=off tox`, you can see them all (1 or 4 bugs according Django version)
Django 1.10 is currently supported in the same range how 1.8 was supported in January. I started to strip code for Django older than 1.8.4. (Django 1.8 - 1.8.3 had an important regression error and our fixes made our code complicated to understand.) Currently no version supports values() and values_list(). Django 1.10 doesn't support only(), defer(), most of raw(). These methods now raise a clear NotImplementedError.

**Comment by hynekcer** [comment]
For your information: everything that was previously problematic (values, values_list, defer, only,raw_queries) is running perfect even in Django 1.10 in my development branch [dev-07](https://github.com/hynekcer/django-salesforce/tree/dev-07). The principle is a little different, the queryset is almost not patched and much more is done by a simulated database cursor. Normal Django database code is much more used, therefore some incompatibilities with the previous django-salesforce are arising because it is more compatible with Django. The code must be cleaned, some heuristics for the new principle should be written exactly again, some tests, documentation etc. There are no major problems or decisions. The end of September is very realistic. At the end of August it should be more clear what is good enough to be incorporated. Then I start to ask more or feedback.

**Comment by philchristensen** [comment]
This one is good to be closed now, right? Or do you want to rename it and use it for tracking purposes?

**Comment by hynekcer** [comment]
Yes. Both is possible: rename or close. I have ignored the import error and accommodated it as a general issue for Django 1.10 because it has no "deferred_class_factory" and I knew that the fix will be bigger than a size usual upgrade after 8 months. I prefer rename.

**Comment by philchristensen** [comment]
I just pushed a release for v0.7.0 including updated support for 1.10 and 1.11.  Is this ticket okay to be closed?

https://pypi.python.org/pypi/django-salesforce/0.7.0

**Comment by hynekcer** [comment]
Yes, the original issue has been fixed early, though the related problems in comments are not fixed still, but the discussion is a bit outdated and repeated and continued elsewhere.
