### ISSUE TITLE
Saving a Lead raises: TypeError: __call__() got an unexpected keyword argument 'query'

### ISSUE THREAD

**Issue by aventurella** [django-salesforce/django-salesforce#170]
Django: 1.10.3
Python: 3.5.2

I can do the following just fine:

```
list(Lead.objects.all())
```

All is well, but when I try to save a Lead:

```
obj = Lead(
        email=email,
        first_name=first_name,
        last_name=last_name,
        status=status,
        lead_source=lead_source
    )

obj.save()
```

I receive the following error:

```
Traceback (most recent call last):
  File "/usr/app/my_project/api/services/crm/tests/test_action_create.py", line 22, in test_ok
    obj = actions.create(
  File "/usr/app/my_project/api/services/crm/actions/create.py", line 22, in create
    obj.save()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.5/site-packages/salesforce/backend/compiler.py", line 476, in execute_sql
    cursor = self.connection.cursor(query=self.query)
TypeError: __call__() got an unexpected keyword argument 'query'
```

**Comment by aventurella** [comment]
Ok! this was my error.

We are creating an application that doesn't use a database.
My unit tests were running under `django.test.SimpleTestCase` which is where I was getting the error. I switched it to `django.test.TestCase` and got an error as well as we have no `default` **ENGINE**.   Switching my unit tests to just `unittest.TestCase` fixed the issue.

I suppose I could also set the salesforce DB as the `default` under `DATABASES` in my settings.

**Comment by hynekcer** [comment]
Yes, it is in Django docs:

> If your tests make any database queries, use subclasses TransactionTestCase or TestCase.

It is not usual to set Salesforce as 'default' (`SALESFORCE_DB_ALIAS = 'salesforce'`) because you probably want `admin` etc. and Django INSTALLED_APPS needs some system tables like `django_*` and `auth_*` that you probably don't want to create on SFDC manually, however if you remove all `''django.*'` apps from INSTALLED_APPS and everything about "admin" from "urls.py" than it is easy.
