### ISSUE TITLE
NotImplementedError when running manage.py makemigrations

### ISSUE THREAD

**Issue by leilabl** [django-salesforce/django-salesforce#186]
Hello,

I have been using django-salesforce and so far the integration has been excellent. I am running into one issue though. When trying to run `manage.py makemigrations` I get the following error:
```
Traceback (most recent call last):
  File "server/manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/project-directory/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/project-directory/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/project-directory/env/lib/python3.6/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/project-directory/env/lib/python3.6/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/project-directory/env/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 100, in handle
    loader.check_consistent_history(connection)
  File "/project-directory/env/lib/python3.6/site-packages/django/db/migrations/loader.py", line 276, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/project-directory/env/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/project-directory/env/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in ensure_schema
    with self.connection.schema_editor() as editor:
  File "/project-directory/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 604, in schema_editor
    'The SchemaEditorClass attribute of this database wrapper is still None')
NotImplementedError: The SchemaEditorClass attribute of this database wrapper is still None
```

More details:
- I am using Django 1.10.
- None of my salesforce models have:
```
Meta:
   managed=True
```
- I haven't set `SALESFORCE_DB_ALIAS` to anything.
- When I run `manage.py check` it identifies no issues.
- If I try `manage.py makemigrations <another-app>` I get the same error.
- If I remove salesforce from `INSTALLED_APPS` the migrations are created and run successfully.

Please let me know if you have any thoughts. I have looked through the open and closed issues and did not find an issue quite similar to this.

Thank you.

**Comment by hynekcer** [comment]
I can not reproduce it with django-salesforce 0.7.2 I guess that you use an old version. Upgrade from 0.6.9 to the new version is seamless.

**Comment by leilabl** [comment]
Thanks @hynekcer! Upgrading fixed the issue. Closing.
