### ISSUE TITLE
inspectdb crash

### ISSUE THREAD

**Issue by pbriet** [django-salesforce/django-salesforce#187]
Hi there,

I recently have issues with the inspectdb command. I don't know if this is due to our recent migration to Django 1.11, or to some modification on the Salesforce account.

Here is the traceback and message : 

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/deployment/virtualenv3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/deployment/virtualenv3.4/lib/python3.4/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deployment/virtualenv3.4/lib/python3.4/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/deployment/virtualenv3.4/lib/python3.4/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/deployment/virtualenv3.4/lib/python3.4/site-packages/django/core/management/commands/inspectdb.py", line 32, in handle
    for line in self.handle_inspection(options):
  File "/deployment/virtualenv3.4/lib/python3.4/site-packages/django/core/management/commands/inspectdb.py", line 169, in handle_inspection
    for meta_line in self.get_meta(table_name, constraints, column_to_field_name):
  File "/deployment/virtualenv3.4/lib/python3.4/site-packages/django/core/management/commands/inspectdb.py", line 279, in get_meta
    tup = '(' + ', '.join("'%s'" % column_to_field_name[c] for c in columns) + ')'
  File "/deployment/virtualenv3.4/lib/python3.4/site-packages/django/core/management/commands/inspectdb.py", line 279, in <genexpr>
    tup = '(' + ', '.join("'%s'" % column_to_field_name[c] for c in columns) + ')'
KeyError: 'I'
```

Thanks,

**Comment by pbriet** [comment]
After investigation : `columns` is a string with one column name, and not a list as expected

**Comment by hynekcer** [comment]
I don't see any "salesforce" string anywhere in the traceback. If django-salesforce package would have been installed correctly, it will use `salesforce/management/commands/inspectdb.py` instead of `django/core/management/commands/inspectdb.py`.

It does not seem to be a problem specific to django-salesforce. Maybe mismatched python paths or an old django-salesforce somewhere or other `salesforce` directory on the path etc. Look at stackoverflow at general problems with django management commands.

Debugging:  
You can simplify the problem investigation by copying `salesforce/management/commands/inspectdb.py` e.g. to `salesforce/management/commands/inspectdb_salesforce.py` and call it `python manage.py inspectdb_salesforce --database=salesforce`, to be sure that inspectdb can't be found in django.core instead. You will probably see "Unknown command: 'inspectdb_salesforce'" on that machine, whilst it will be ok on other machine or in a clean virtualenv .

**Comment by hynekcer** [comment]
(FYI: It is a statnard extension. The customized inspectdb command will call a normal inspectdb if the database does not use the salesforce backend.)

**Comment by pbriet** [comment]
Thanks for the response.

Indeed, for some weird reason, django-salesforce disappeared from my `INSTALLED_APPS`... that's why the default inspectdb was executed.

Sorry for the inconvenience,
Cheers,
