### ISSUE TITLE
Where to find security token

### ISSUE THREAD

**Issue by natea** [django-salesforce/django-salesforce#214]
I'm using an app edx-salesforce that makes use of django-salesforce, and when I try to run the sync command, I get this error:

```
$ python manage.py sync_salesforce -s localhost -o example.com --settings=settings.local
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    return module.Command()
  File "/Users/nateaune/Documents/code/hawthorn/edx-salesforce/edx_salesforce/management/commands/sync_salesforce.py", line 45, in __init__
    self.pricebook = Pricebook2.objects.get(is_standard=True)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/backend/manager.py", line 30, in get_queryset
    if not router.is_sf_database(self.db):
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/router.py", line 27, in is_sf_database
    engine = connections[db].settings_dict['ENGINE']
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/db/utils.py", line 212, in __getitem__
    conn = backend.DatabaseWrapper(db, alias)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/backend/base.py", line 114, in __init__
    self.make_session()
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/backend/base.py", line 124, in make_session
    sf_instance_url = sf_session.auth.instance_url
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/auth.py", line 144, in instance_url
    return self.get_auth()['instance_url']
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/auth.py", line 118, in get_auth
    oauth_data[db_alias] = self.authenticate()
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/auth.py", line 198, in authenticate
    raise LookupError("oauth failed: %s: %s" % (settings_dict['USER'], response.text))
LookupError: oauth failed: developer@appsembler.com: {"error":"invalid_grant","error_description":"authentication failure"}
```

I saw in this comment (https://github.com/django-salesforce/django-salesforce/issues/83#issuecomment-60832767) that you must append the token after the password, unless you whitelist your IP address in the Security -> Network Access. I have whitelisted my IP address, but still getting the same error.

Anyone know where to find this token? It's not obvious on the Connected App screen.

**Comment by philchristensen** [comment]
So, if you've whitelisted your IP address, it's unlikely that this is the issue, but the token in question is sent to you via email any time you change your password. If you change your password, you'll get a new security token as well.

**Comment by natea** [comment]
I whitelisted my IP address, but then un-whitelisted it because I read somewhere that if you whitelist your address, then the password+token won't work anymore.

I have not changed my password, so it's unclear why the password+token combo is not working and resulting in that error: `LookupError: oauth failed: developer@appsembler.com: {"error":"invalid_grant","error_description":"authentication failure"}`

Do you have any other suggestions that I could try to debug this issue?

**Comment by philchristensen** [comment]
A good place to start is to confirm your connection strings and so forth with a tool like the [Salesforce CLI](https://developer.salesforce.com/tools/sfdxcli)

**Comment by natea** [comment]
Thanks! I didn't know about the Salesforce CLI. I was just using curl and
Postman (Chrome extension) to test basic connection strings and credentials.
