### ISSUE TITLE
Update to Django 2.2 LTS planned?

### ISSUE THREAD

**Issue by kunambi** [django-salesforce/django-salesforce#230]
Hi,

This is perhaps a continuation of #211, but for Djangos latest LTS version that has been out for a couple of weeks now.

According to your current README file, you started testing on Beta1 of the 2.2 version.
```
Python 2.7.9+, 3.4 to 3.7, Django 1.10, 1.11, 2.0, 2.1 and 2.2 (tested on beta 1).
```

When trying to run our Django 2.2 project, we see the following error:
```
Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\htdocs\env\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\htdocs\env\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\htdocs\env\lib\site-packages\django\utils\autoreload.py", line 77, in raise_last_exception
    raise _exception[0](_exception[1]).with_traceback(_exception[2])
  File "C:\htdocs\env\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\htdocs\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\htdocs\env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\htdocs\env\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\htdocs\env\lib\site-packages\salesforce\__init__.py", line 27, in <module>
    raise ImportError("Django version between 1.8.4 and 1.11.x is required "
ImportError: Django version between 1.8.4 and 1.11.x is required for this django-salesforce.
```

We hope/wish that creating the last tests for 2.2 shouldn't take too long, and should be easy to implement. Do you have any idea if/when this will be done?

**Comment by kunambi** [comment]
Unfortunatelly I had the wrong information about which version we ran internally. Closing this issue.

**Comment by hynekcer** [comment]
Only the README text is to be updated for Django 2.2 now. (after April 1) #228
