### ISSUE TITLE
Not compatible with django-debug-toolbar

### ISSUE THREAD

**Issue by l-kotzur** [django-salesforce/django-salesforce#247]
Hey there,

first thanks for the great package. 

In order to avoid future headache of other developers, I just want to point out that django-salesforce was not compatible with the [django-debug-toolbar](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html) for me. 

I got following error, running them together in a local environment:
```
 ...
  File ".../lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)

  File ".../lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,

  File ".../lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

  File ".../lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)

  File ".../lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File ".../lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)

  File ".../lib/python3.7/site-packages/salesforce/backend/compiler.py", line 434, in execute_sql
    cursor.execute(sql, params)

  File ".../lib/python3.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 192, in execute
    return self._record(self.cursor.execute, sql, params)

  File ".../lib/python3.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 126, in _record
    return method(sql, params)

  File ".../lib/python3.7/site-packages/salesforce/backend/utils.py", line 181, in execute
    self.execute_select(q, args)

  File ".../lib/python3.7/site-packages/salesforce/backend/utils.py", line 250, in execute_select
    self.cursor.execute(soql, args, query_all=is_query_all)

  File ".../lib/python3.7/site-packages/salesforce/dbapi/driver.py", line 533, in execute
    raise ProgrammingError("Unexpected command '{}'".format(sqltype))

salesforce.dbapi.exceptions.ProgrammingError: Unexpected command 'INSERT'
```
Deactivating the django-debug-toolbar solved this problem.

Do not hesitate to close this issue, but perhaps it helps others who will run into similar problems.

Happy christmas,
Leander

**Comment by hynekcer** [comment]
The fix was simple: [commit 64fc6a6](https://github.com/hynekcer/django-salesforce/commit/64fc6a67fcdb06bb62d485673e943a3eaaa9ad46). Try it please.

If it is fixed enough I should add tests before we commit it to master.

The problem was that debug-toolbar has wrapped the method `connection.cursor()` by `debug_toolbar.panels.sql.tracking.cursor()`. The solution was simple: _Single Responsibility Principle_: set the attributes of our cursor only by custom methods of cursor and never access them directly by a query compiler.

**Comment by l-kotzur** [comment]
Thanks for the fast response and fix-proposal.

I tried it out, but unfortunately it still throws the same error:
```
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File ".../lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File ".../lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File ".../lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File ".../lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File ".../workspace/hps/webapp/webapp/piceaconfig/views.py", line 71, in post
    account.save()
  File ".../lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File ".../lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File ".../lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File ".../lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File ".../lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File ".../lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File ".../workspace/sandbox/django-salesforce/salesforce/backend/compiler.py", line 434, in execute_sql
    cursor.execute(sql, params)
  File ".../lib/python3.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 192, in execute
    return self._record(self.cursor.execute, sql, params)
  File ".../lib/python3.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 126, in _record
    return method(sql, params)
  File ".../workspace/sandbox/django-salesforce/salesforce/backend/utils.py", line 181, in execute
    self.execute_select(q, args)
  File ".../workspace/sandbox/django-salesforce/salesforce/backend/utils.py", line 250, in execute_select
    self.cursor.execute(soql, args, query_all=is_query_all)
  File ".../workspace/sandbox/django-salesforce/salesforce/dbapi/driver.py", line 533, in execute
    raise ProgrammingError("Unexpected command '{}'".format(sqltype))
salesforce.dbapi.exceptions.ProgrammingError: Unexpected command 'INSERT'
```

**Comment by hynekcer** [comment]
I can not reproduce it after the fix. OK. I will commit a simple demo project soon that works for me with django-debug-toolbar. You can extend it by something that raises the exception.

No version was specified. I did run tests in a new virtual environment with the newest versions.  (Django-salesforce 0.9, Python 3.8, Django 3.0, django-debug-toolbar 2.1) It also helps to be sure that the patched source `salesforce/backend/compiler.py` and the installed `.../workspace/sandbox/django-salesforce/salesforce/backend/compiler.py` are the same.

**Comment by hynekcer** [comment]
I committed a branch `debug-toolbar` that you can customize to can demonstrate the issue that the fix did not help you.

``` bash
# !! start the cloning in a new dir ...
git clone https://github.com/django-salesforce/django-salesforce.git
cd django-salesforce
# copy your local settings with your sandbox DATABASES = {'salesforce'...}
# into salesforce/testrunner/local_settings.py
git checkout debug-toolbar
python3 -m venv .env
source .env/bin/activate
pip install django-debug-toolbar -r requirements.txt
python manage.py migrate --settings=tests.t_debug_toolbar.settings
python manage.py runserver --settings=tests.t_debug_toolbar.settings
```

Open this URL in a browser:  http://127.0.0.1:8000/account_insert_delete/  
You should see a simple page with a string "OK" and a Django debug toolbar, where you see three SQL commands for INSERT, UPDATE and DELETE. These SQL commands are never executed by [Salesforce SOQL](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_sosl_intro.htm), but it is an equivalent, what is done in the background by it at the same time.

If you open the URL http://127.0.0.1:8000/  you will see two SQL commands. (The first red item is a "django_session" query in the default database) The last one green is the exact SOQL command executed by Salesforce. If you click "EXPLAIN" you will see [Salesforce EXPLAIN](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_query_explain.htm) output (the actual execution plan and eventually more execution plans with less priority that have been analysed by the Salesforce planner).

Modify that code to reproduce your issue or send another complete simple example.

**Comment by l-kotzur** [comment]
It works! Thank you! Your proposed test and the full stack.

I did not checkout the correct commit for the fix... -.- Sorry. I hope that you wanted to integrate the testing anyway.

Thanks for the superfast support.

**Comment by hynekcer** [comment]
That's OK. also thanks for fast response. The extra work was really only to write the last comments.
