### ISSUE TITLE
Cannot configure SF_PK

### ISSUE THREAD

**Issue by kylemassimilian** [django-salesforce/django-salesforce#334]
I'm unable to get past this error while trying to execute a simple test to interact with my Salesforce instance. I have been able to successfully interact with SF objects (such as Account) through the shell, but I am not able to in my script. 

Here is my test:
```

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cdp.settings')
django.setup()
...
SF_PK='id'
account1 = Account.objects.get(PersonEmail='kyle@vellaclean.com')
print(account1)

```

Could someone please help me understand what I'm doing incorrectly here? SF_PK is defined in my settings.py:

```
## Salesforce setting for primary key
SF_PK='id'
```

stacktrace:

```
`(cdp-J3b73aRa-py3.12) kylemassimilian@Kyles-MBP-2 klaviyo % poetry run python3 services.py
Traceback (most recent call last):
  File "/Users/kylemassimilian/Desktop/Vella/Software Engineering/Stack/Microservices/cdp/klaviyo/services.py", line 8, in <module>
    from models import Account, Opportunity
  File "/Users/kylemassimilian/Desktop/Vella/Software Engineering/Stack/Microservices/cdp/klaviyo/models.py", line 2, in <module>
    from salesforce import models as sf_models
  File "/Users/kylemassimilian/Library/Caches/pypoetry/virtualenvs/cdp-J3b73aRa-py3.12/lib/python3.12/site-packages/salesforce/models.py", line 29, in <module>
    from salesforce.fields import (  # pylint:disable=useless-import-alias
  File "/Users/kylemassimilian/Library/Caches/pypoetry/virtualenvs/cdp-J3b73aRa-py3.12/lib/python3.12/site-packages/salesforce/fields.py", line 33, in <module>
    SF_PK = getattr(settings, 'SF_PK', 'id')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kylemassimilian/Library/Caches/pypoetry/virtualenvs/cdp-J3b73aRa-py3.12/lib/python3.12/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/kylemassimilian/Library/Caches/pypoetry/virtualenvs/cdp-J3b73aRa-py3.12/lib/python3.12/site-packages/django/conf/__init__.py", line 63, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting SF_PK, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`
```

Thank you

**Comment by hynekcer** [comment]
The stacktrace indicates that it was a general problem with missing Django settings path configuration, not related to django-salesforce. "SF_PK" happened to be the first value where settings were used.

The lowercase primary key "id" is a default value and not necessary to specify it. SF_PK is useful only you would  prefer capitalized primary keys "Id" in your code.
