### ISSUE TITLE
Migrations in django 1.7 after updating from 1.6

### ISSUE THREAD

**Issue by chromakey** [django-salesforce/django-salesforce#97]
Hi Everyone,
After migrating from django 1.6 to 1.7, I'm not able to run any migrations without commenting out my salesforce models.  I get the following traceback:

```
python manage.py migrate airports --settings=avl.settings.local
Operations to perform:
  Apply all migrations: airports
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/.virtualenvs/avl/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/srv/.virtualenvs/avl/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/.virtualenvs/avl/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/srv/.virtualenvs/avl/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/srv/.virtualenvs/avl/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 154, in handle
    ProjectState.from_apps(apps),
  File "/srv/.virtualenvs/avl/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 108, in from_apps
    model_state = ModelState.from_model(model)
  File "/srv/.virtualenvs/avl/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 180, in from_model
    fields.append((name, field_class(*args, **kwargs)))
  File "/srv/.virtualenvs/avl/local/lib/python2.7/site-packages/salesforce/fields.py", line 208, in __init__
    related_object = args[0]
IndexError: tuple index out of range
```

I have my salesforce model in a separate app called "sfdata".  Here's sfdata/models.py:

```python
from salesforce import models
from salesforce.models import SalesforceModel, READ_ONLY

class Account(SalesforceModel):
    Name = models.CharField(max_length=255, verbose_name='Account Name')
    BillingAddress = models.CharField(max_length=255, verbose_name='Billing Address')

class Opportunity(SalesforceModel):
    Name = models.CharField(max_length=120, verbose_name='Name', sf_read_only=READ_ONLY)
    Account = models.ForeignKey(Account, db_column='AccountId')
```

The only place I utilize this model is in my "contracts" app here:
```python
#contracts/views.py
...
oppy_id = asr_record.sf_oppy_id.split('/')[-1]
oppy_id = oppy_id.split('?')[0]
oppy = Opportunity.objects.get(id=oppy_id)
address_json = oppy.Account.BillingAddress
...
```

Here's the relevant portions of my settings file:
```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'avl',
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASS'],
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            "init_command": "SET foreign_key_checks = 0;",
        },
    },
    'salesforce': {
        'ENGINE': 'salesforce.backend',
        'CONSUMER_KEY': os.environ['SF_KEY'],
        'CONSUMER_SECRET': os.environ['SF_SECRET'],
        'USER': os.environ['SF_USER'],
        'PASSWORD': os.environ['SF_PASS'],
        'HOST': 'https://login.salesforce.com',
    },
}

DATABASE_ROUTERS = [
    "salesforce.router.ModelRouter"
]
```

Any thoughts are appreciated.  Thanks!

**Comment by chromakey** [comment]
To further refine, I'm able to successfully run migrations if I comment out only this line from sfdata/models.py:

```python
Account = models.ForeignKey(Account, db_column='AccountId')
```

**Comment by chromakey** [comment]
One of these days I won't jump the gun so early.  In case anyone else ever stumbles upon this for some reason:

```python
Account = models.ForeignKey(Account, db_column='AccountId')
```

Should be:

```python
account = models.ForeignKey(Account, on_delete=models.DO_NOTHING, blank=True, null=True)
```

I can't remember how I even arrived at the original code it's been so long.  Apologies and thanks for a great library!

**Comment by philchristensen** [comment]
No worries @chromakey , glad you're all set.
